# Generated by Django 4.2 on 2023-04-27 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ на пошив', 'verbose_name_plural': 'Заказы на пошивы'},
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('oreder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailoring.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailoring.product')),
            ],
            options={
                'verbose_name': 'Заказ товара',
                'verbose_name_plural': 'Заказ товаров',
            },
        ),
    ]
