# Generated by Django 4.2 on 2023-04-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0002_alter_order_options_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'slkdjf', 'verbose_name_plural': 'lskjdflkd'},
        ),
    ]
