# Generated by Django 4.2 on 2023-04-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0003_alter_orderproduct_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Заказ товара', 'verbose_name_plural': 'Заказ товаров'},
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='oreder',
            new_name='order',
        ),
    ]
