# Generated by Django 4.2 on 2023-04-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0005_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
