# Generated by Django 4.2 on 2023-04-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0008_orderstatus_alter_orderproduct_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='orders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tailoring.order'),
            preserve_default=False,
        ),
    ]
