# Generated by Django 4.2 on 2023-04-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0010_remove_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'Красный'), ('blue', 'Синий'), ('green', 'Зеленый'), ('black', 'Черный'), ('white', 'Белый')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=1),
        ),
    ]
