# Generated by Django 4.2 on 2023-04-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0011_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
