# Generated by Django 4.2 on 2023-04-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0013_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
    ]
