# Generated by Django 4.2 on 2023-04-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0018_alter_order_customer_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='order',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
