# Generated by Django 4.2 on 2023-04-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0019_remove_document_order_delete_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={},
        ),
    ]
