# Generated by Django 4.2 on 2023-04-29 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tailoring', '0023_orderstatus_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='customuser',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
