# Generated by Django 4.2 on 2023-05-01 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0027_rename_orders_orderstatus_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='tailoring.ordertailoring'),
        ),
    ]
