# Generated by Django 4.2 on 2023-05-02 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0028_alter_orderstatus_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tailoring.orderproduct'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_tailoring',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tailoring.ordertailoring'),
        ),
    ]
