# Generated by Django 4.2 on 2023-04-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnerRequest',
        ),
    ]
